# Generated by Django 6.0.3 on 2026-03-04 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nominations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='review_cycles.reviewcycle')),
                ('nominated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_nominations', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_nominations', to=settings.AUTH_USER_MODEL)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nominations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peer_nominations',
                'unique_together': {('cycle', 'reviewee', 'peer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewerTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_type', models.CharField(choices=[('SELF', 'Self'), ('MANAGER', 'Manager'), ('PEER', 'Peer'), ('DIRECT_REPORT', 'Direct Report')], max_length=20)),
                ('anonymity_mode', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('SEMI_ANONYMOUS', 'Semi Anonymous'), ('TRANSPARENT', 'Transparent')], default='TRANSPARENT', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked')], default='CREATED', max_length=15)),
                ('draft_answers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='review_cycles.reviewcycle')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_reviewee', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_tasks',
                'unique_together': {('cycle', 'reviewee', 'reviewer')},
            },
        ),
    ]
