# Generated by Django 6.0.3 on 2026-03-04 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_cycles', '0001_initial'),
        ('reviewer_workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviewer_workflow.reviewertask')),
            ],
            options={
                'db_table': 'feedback_responses',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_cycles.templatequestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackresponse')),
            ],
            options={
                'db_table': 'feedback_answers',
            },
        ),
        migrations.CreateModel(
            name='AggregatedResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manager_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_results', to='review_cycles.reviewcycle')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aggregated_results',
                'unique_together': {('cycle', 'reviewee')},
            },
        ),
    ]
