# Generated by Django 6.0.3 on 2026-03-27 09:40

import apps.client_feedback.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedbackSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'client_feedback_sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ClientFeedbackQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('RATING', 'Rating (1–5 stars)'), ('TEXT', 'Text (open-ended)'), ('RATING_WITH_TEXT', 'Rating + Text'), ('YES_NO', 'Yes / No'), ('NPS', 'NPS (0–10 scale)')], default='RATING', max_length=20)),
                ('applies_to', models.CharField(choices=[('EACH_EMPLOYEE', 'Each Employee'), ('TEAM_OVERALL', 'Team Overall')], default='EACH_EMPLOYEE', max_length=20)),
                ('helper_text', models.CharField(blank=True, default='', max_length=400)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='client_feedback.clientfeedbacksection')),
            ],
            options={
                'db_table': 'client_feedback_questions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ClientFeedbackTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_feedback_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_feedback_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientfeedbacksection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='client_feedback.clientfeedbacktemplate'),
        ),
        migrations.CreateModel(
            name='ClientFeedbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=apps.client_feedback.models._generate_token, editable=False, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(blank=True, related_name='client_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='client_feedback.clientfeedbacktemplate')),
            ],
            options={
                'db_table': 'client_feedback_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFeedbackAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, default='')),
                ('yes_no_value', models.BooleanField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='client_feedback.clientfeedbackquestion')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='client_feedback.clientfeedbackrequest')),
            ],
            options={
                'db_table': 'client_feedback_answers',
                'unique_together': {('request', 'question', 'employee')},
            },
        ),
    ]
