# Generated by Django 6.0.3 on 2026-03-04 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('NOMINATION', 'Nomination'), ('FINALIZED', 'Finalized'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('RESULTS_RELEASED', 'Results Released'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('peer_enabled', models.BooleanField(default=False)),
                ('peer_min_count', models.IntegerField(blank=True, null=True)),
                ('peer_max_count', models.IntegerField(blank=True, null=True)),
                ('peer_threshold', models.IntegerField(default=3)),
                ('peer_anonymity', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('SEMI_ANONYMOUS', 'Semi Anonymous'), ('TRANSPARENT', 'Transparent')], default='ANONYMOUS', max_length=20)),
                ('manager_anonymity', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('SEMI_ANONYMOUS', 'Semi Anonymous'), ('TRANSPARENT', 'Transparent')], default='TRANSPARENT', max_length=20)),
                ('self_anonymity', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('SEMI_ANONYMOUS', 'Semi Anonymous'), ('TRANSPARENT', 'Transparent')], default='TRANSPARENT', max_length=20)),
                ('nomination_deadline', models.DateTimeField(blank=True, null=True)),
                ('review_deadline', models.DateTimeField()),
                ('quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True)),
                ('quarter_year', models.IntegerField(blank=True, null=True)),
                ('nomination_approval_mode', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('results_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='review_cycles.template')),
            ],
            options={
                'db_table': 'review_cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='review_cycles.template')),
            ],
            options={
                'db_table': 'template_sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('RATING', 'Rating'), ('TEXT', 'Text'), ('MULTI_CHOICE', 'Multiple Choice')], default='RATING', max_length=20)),
                ('rating_scale_min', models.IntegerField(blank=True, null=True)),
                ('rating_scale_max', models.IntegerField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='review_cycles.templatesection')),
            ],
            options={
                'db_table': 'template_questions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CycleParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_participations', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='review_cycles.reviewcycle')),
            ],
            options={
                'db_table': 'cycle_participants',
                'unique_together': {('cycle', 'user')},
            },
        ),
    ]
